### ISSUE TITLE
imagePullSecrets per pod

### ISSUE THREAD

**Issue by ibnHatab** [jugatsu/gitlab-registry-kubernetes-secrets-howto#1]
As per https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
You have to specify imagePullSecrets per pod

apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: <your-private-image>
  imagePullSecrets:
  - name: regcred

**Comment by jugatsu** [comment]
I do. )

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: $DOCKER_IMAGE_FULL_PATH
      imagePullPolicy: Always
  imagePullSecrets:
    - name: gitlab-registry
```
